### PR TITLE
Fix button shadow problems

### LINKED ISSUE #11: Fix iOS button shadow problems

### PR DESCRIPTION
**Pull request by Zappi**
Closes #11

### CODE REVIEW

File: src/components/home/EventListElementComponent.tsx [hunk 1]
```diff
@@ -58,18 +57,25 @@ const EventListElementComponent = (props: Props) => {
...
-        offset={[0, 1]} paintInside={true} style={{ alignSelf: 'stretch', borderRadius: 5 }}>
-        <TouchableOpacity onPress={props.onPress} activeOpacity={0.8}>
-          <View style={Cs.unsentEventsContainer} >
-            <Text style={[Ts.eventListElementTitle, { color: Colors.dangerButton1 }]}>{title}</Text>
-            <Text style={Ts.eventListElementTextClear}>{displayDateTime()}</Text>
-            <Text style={Ts.eventListElementTextFaded}>{t('observations in list') + ': ' + observationCount() + ' ' + (observationCount() === 1 ? t('piece') : t('pieces'))}</Text>
-          </View>
-        </TouchableOpacity>
-      </Shadow>
+      <TouchableOpacity onPress={props.onPress} activeOpacity={0.8} style={{
```
Comment (rpulkka) [inline src/components/home/EventListElementComponent.tsx:63]: Container styles should be imported from /styles/ContainerStyles.tsx. Create a new style into /styles/ContainerStyles.tsx, for example "buttonShadowContainer". Import it like this: "import Cs from '../styles/ContainerStyles.tsx'". Repeat for different shadow styles, reuse if possible. If shadow styles differ by only one attribute, you can use 'style={[Cs.buttonShadowContainer, { shadowColor: Colors.dangerShadow }]}'.

File: src/styles/Colors.tsx [hunk 2]
```diff
@@ -21,16 +21,16 @@ export default {
 
   //button colors and their shadows
   neutralButton: '#FCFDFD',
-  neutralShadow: '#141B1F50', //shadow colors use #rrggbbaa syntax, where aa is the alpha/(transparency) channel
+  neutralShadow: '#141B1F', //shadow colors use #rrggbbaa syntax, where aa is the alpha/(transparency) channel
   primaryButton1: '#22ABC3',
```
Comment (rpulkka) [inline src/styles/Colors.tsx:25]: Remove my old comment, seems to be redundant after the new changes.

File: src/components/general/ButtonComponent.tsx [hunk 3]
```diff
@@ -24,13 +23,22 @@ type Props = {
 }
 
 const ButtonComponent = (props: Props) => {
-
   return (
-    <Shadow startColor={props.shadowColor} endColor={props.shadowColor} distance={0}
-      sides={{ 'start': false, 'end': false, 'top': false, 'bottom': true }} offset={[0, 2]}
-      paintInside={true} style={{ borderRadius: 5, width: '100%' }}>
+    // <Shadow startColor={props.shadowColor} endColor={props.shadowColor} distance={0}
```
Comment (rpulkka) [inline src/components/general/ButtonComponent.tsx:27]: The commented code can be removed IMO.

**Review by rpulkka — CHANGES_REQUESTED** [review]
Changes regarding the use of style files requested, let me know if you need more details on how to fix.

**Review by rpulkka — APPROVED** [review]
Nice work, approving! :)
